[package]
name = "ydcv-2"
description = "A rust version of YouDao Console Version"
repository = "https://github.com/eatradish/ydcv-2"
readme = "README.md"
license = "GPL-2.0"
version = "0.7.0"
authors = ["Jiachen Yang <farseerfc@gmail.com>", "sakiiily@aosc.io"]
edition = "2024"

[[bin]]
name = "ydcv"
path = "./src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
env_logger = "^0.11"
rustyline = "15"
log = "^0.4"
atty = "^0.2"
htmlescape = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["blocking"] }
rand = "0.9"
scraper = "0.23"
arboard = { version = "3.5.0", optional = true, default-features = false, features = ["wayland-data-control"] }
anyhow = "1"

[target.'cfg(windows)'.dependencies]
winrt-notification =    { version = "^0.5", optional = true }

[target.'cfg(unix)'.dependencies]
notify-rust =           { version = "^4.3", optional = true }

[features]
default = ["notify", "clipboard", "rustls"]
native-tls = ["reqwest/native-tls"]
notify = ["notify-rust", "winrt-notification"]
clipboard = ["arboard"]
rustls = ["reqwest/rustls-tls"]

[profile.release-lto]
inherits = "release"
lto = true
